services:
  docs:
    build:
      context: .
      args:
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL:-http://localhost:3000}
        DEPLOYMENT_VERSION: ${DEPLOYMENT_VERSION:-local}
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      APP_REVISION: ${DEPLOYMENT_VERSION:-local}
      HOSTNAME: 0.0.0.0
    restart: unless-stopped
