additionalProperties: false
properties:
  fromUserID:
    type: string
    minLength: 1
  groupID:
    type: string
    minLength: 1
  handleResult:
    format: int32
    type: integer
    enum:
      - -1
      - 1
  handledMsg:
    type: string
type: object
required:
  - groupID
  - fromUserID
  - handleResult
